export const GAME_GENRES_DISPLAYABLE = {
	action: 'Acción',
	adventure: 'Aventura',
	arcade: 'Arcade',
	platform: 'Plataforma',
	puzzle: 'Puzzle',
	racing: 'Carreras',
	rol: 'Rol',
	shooter: 'Shooter',
	sports: 'Deportes',
	strategy: 'Estrategia',
	rpg: 'RPG',
	simulation: 'Simulación',
	openWorld: 'Mundo Abierto',
	indie: 'Indie',
	isometric: 'Isométrico',
	stealth: 'Sigilo',
	survival: 'Supervivencia',
	fantasy: 'Fantasía',
	zomby: 'Zomby',
	terror: 'Terror',
	tps: 'TPS',
	metroidvania: 'Metroidvania',
	construction: 'Construcción',
	sandbox: 'Sandbox',
	driving: 'Conducción',
	twod: '2D',
	hackAndSlash: 'Hack & Slash',
	humor: 'Humor',
	poinAndClick: 'Punto & Click',
	realTimeStrategy: 'Estrategia en Tiempo Real',
	fighting: 'Lucha',
	anime: 'Anime',
	fps: 'FPS',
	futbol: 'Fútbol',
	medieval: 'Medieval',
	motorsports: 'Motosports',
	likesouls: 'Like Souls',
	rolRpg: 'Rol/RPG',
	souls: 'Souls',
	scifi: 'Ciencia Ficción',
	historic: 'Histórico',
	retro: 'Retro',
};

export enum GAME_GENRES {
	action = 'action',
	adventure = 'adventure',
	arcade = 'arcade',
	platform = 'platform',
	puzzle = 'puzzle',
	racing = 'racing',
	rol = 'rol',
	shooter = 'shooter',
	sports = 'sports',
	strategy = 'strategy',
	rpg = 'rpg',
	simulation = 'simulation',
	openWorld = 'openWorld',
	indie = 'indie',
	isometric = 'isometric',
	stealth = 'stealth',
	survival = 'survival',
	fantasy = 'fantasy',
	zomby = 'zomby',
	terror = 'terror',
	tps = 'tps',
	metroidvania = 'metroidvania',
	construction = 'construction',
	sandbox = 'sandbox',
	driving = 'driving',
	twod = '2d',
	hackAndSlash = 'hackAndSlash',
	humor = 'humor',
	poinAndClick = 'pointAndClick',
	realTimeStrategy = 'realTimeStrategy',
	fighting = 'fighting',
	anime = 'anime',
	fps = 'fps',
	futbol = 'futbol',
	medieval = 'medieval',
	motorsports = 'motorsports',
	likesouls = 'likesouls',
	rolRpg = 'rolRpg',
	souls = 'souls',
	scifi = 'scifi',
	historic = 'historic',
	retro = 'retro',
}
