export const GAME_GENRES_DISPLAYABLE = {
	action: 'Acción',
	adventure: 'Aventura',
	arcade: 'Arcade',
	platform: 'Plataforma',
	puzzle: 'Puzzle',
	racing: 'Carreras',
	rol: 'Rol',
	shooter: 'Shooter',
	sports: 'Deportes',
	strategy: 'Estrategia',
	rpg: 'RPG',
	simulation: 'Simulación',
	openWorld: 'Mundo Abierto',
	indie: 'Indie',
	isometric: 'Isométrico',
	stealth: 'Sigilo',
	survival: 'Supervivencia',
	fantasy: 'Fantasía',
	zomby: 'Zomby',
	terror: 'Terror',
};

export enum GAME_GENRES {
	action = 'action',
	adventure = 'adventure',
	arcade = 'arcade',
	platform = 'platform',
	puzzle = 'puzzle',
	racing = 'racing',
	rol = 'rol',
	shooter = 'shooter',
	sports = 'sports',
	strategy = 'strategy',
	rpg = 'rpg',
	simulation = 'simulation',
	openWorld = 'openWorld',
	indie = 'indie',
	isometric = 'isometric',
	stealth = 'stealth',
	survival = 'survival',
	fantasy = 'fantasy',
	zomby = 'zomby',
	terror = 'terror',
}
